# Generated by Django 5.2.5 on 2025-11-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaktibackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='badge_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='rank',
            field=models.CharField(max_length=100),
        ),
    ]
